name: 'Protoc Helper'
description: 'Runs the protoc tool and includes the golang plugin'
author: '@spolab'

inputs:
  args:
    description: 'Arguments for protoc'
    required: true
    default: '-h'

runs:
    using: 'docker'
    image: 'docker://ghcr.io/spolab/protoc-action:v0.0.11'
    args:
      - ${{ inputs.args }}

branding:
  icon: 'command'
  color: 'blue'