name: Release Worklow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}    

      - name: Release Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: toremo/protoc-action:${{ github.ref_name }}
          push: true
