name: Release Worklow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}    

      - name: Release Docker Image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ghcr.io/spolab/protoc-action:${{ github.ref_name }}
          labels: ${{steps.meta.outputs.labels}}
          push: true
